### PR TITLE
Add [code=language]

### PR DESCRIPTION
**Pull request by BoboTiG**
With this PR, you will be able to:
- easily add code highlighting using [code=language]...[/code]
- parse code into articles but into comments and links too
- using only [code][/code] will ouput simply as `<code></code>`

You have to define manually into config/config-advanced.ini (as it is ignored into .gitignore):

    CODE_HIGHTLIGHT_FMT = '<pre data-language="%s"><code>%s</code></pre>'

Like that, everybody can custom the output of [code=language][/code] accordingly to its code highlighter library.

### CODE REVIEW

**Comment by timovn** [comment]
Function `parse_texte_paragraphs()` is not longer called here.

**Comment by BoboTiG** [comment]
Is it a required? It adds lots of spaces:

screenshot

**Comment by timovn** [comment]
It adds paragraphs `<p></p>`, not only `<br>`

**Comment by BoboTiG** [comment]
Updated.

**Comment by BoboTiG** [comment]
Could you review this patch? I tested on the dev branch and I saw extra `<br>` added after each `<li>` of lists. There is something wrong, I investigate.

**Comment by BoboTiG** [comment]
I found the error, it was the call to `preg_replace()` at the wrong line.

**Comment by timovn** [comment]
I'll check this thoroughly tomorrow.

Adding a `data-language` is actually a good idea and I like it. Same for putting the `[code]` parsing outside, but there might remain some side effects. I’ll have to test all this.

**Comment by timovn** [comment]
I just implemented all this in commit d1b8e20.

I didn’t merge it because of some incoherence, so I rewrote your function.
It seem to work. I also added some styles. for the `<pre>` in admin and public themes, including some nice tweak using the `data-language` attribute.

Besides, I didn’t fell necessary to include a new variable `CODE_HIGHTLIGHT_FMT`.
I looked at some hightlighters ([highlight.js](https://github.com/isagalaev/highlight.js), [prism.js](https://github.com/PrismJS/prism) and [rainbow](https://github.com/ccampbell/rainbow)). One is using `data-*` and the two others are using classes.
IMHO, the usage of data-* is totally appropriate here, so I kept that.

Also, I may now work on merging the functions `formatage_wiki()`, `formatage_commentaires()` and `formatage_links()`, keeping the fact that more freedom has to be given in formatting articles than formatting comments (which should not allow plain HTML, for instance) or links.

**Comment by BoboTiG** [comment]
It seems really nice!

**Pull request closed without merging**
